# Optimization Task
num_feature_basis_functions: 1
trajectory_duration: 8.0
num_time_steps: 80
publish_trajectory_markers: False
publish_best_trajectory_marker: True
publish_distance_field_marker: False
publish_collision_model_markers: False

# Collision Space
collision_space:
  size_x: 8.5 # The X dimension in meters of the volume to represent
  size_y: 6.0 # The Y dimension in meters of the volume to represent
  size_z: 4.0 # The Z dimension in meters of the volume to represent
  origin_x: 0.0 
  origin_y: 0.0 
  origin_z: 1.5 
  resolution: 0.04    
  collision_tolerance: 0.01
  max_propagation_distance: 4.0

# STOMP 
max_iterations: 120
max_iterations_after_collision_free: 10
max_rollouts: 100
min_rollouts: 10
num_rollouts_per_iteration: 60
use_noise_adaptation: true
#noise_stddev: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
#noise_stddev: [4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0]
#noise_min_stddev: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
#noise_stddev: [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
#noise_min_stddev: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]

noise_stddev: [0.3, 0.4, 1.0, 0.4, 0.3, 0.3, 0.3]
noise_min_stddev: [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
noise_decay:  [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
write_to_file: false
use_openmp: false

features: 
-
  class: stomp_moveit_interface/CollisionFeature
  report_validity: false # report state validity based on distance field
  collision_clearance: 0.06
  debug_collisions: false
