<?xml version="1.0" ?>

<!--Generates a urdf from the macro in kr210_macro.xacro -->

<robot name="test_kr210" xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:include filename="$(find stomp_test_support)/urdf/kr210l150_macro.xacro"/>
	<xacro:kuka_kr210l150 prefix=""/>

  <xacro:property name="rail_cross_section" value="0.1"/>

  <link name="world"/>

  <link name="rail">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="4 ${rail_cross_section} ${rail_cross_section}"/>
      </geometry>
      <material name="yellow">
       <color rgba="1.0 1.0 0 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <box size="4 0.1 0.1"/>
      </geometry>
      <material name="yellow">
       <color rgba="1.0 1.0 0 1.0"/>
      </material>
    </collision>   
  </link>


  <xacro:property name="cylinder_height" value="8.0"/>
  <link name="obstacle_cylinder">
    <visual>
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.2" length="${cylinder_height}"/>
      </geometry>
     <material name="cyan">
       <color rgba="0 1.0 1.0 1.0"/>
     </material>
    </visual>
    <collision>
      <origin xyz="0 0 0"/>
      <geometry>
        <cylinder radius="0.2" length="${cylinder_height}"/>
      </geometry>
     <material name="cyan">
       <color rgba="0 1.0 1.0 1.0"/>
     </material>
    </collision>
  </link>

  <joint name="world_to_rails" type="fixed">
    <parent link="world" />
    <child link="rail" />
    <origin xyz="0 0 0"/>
  </joint>

  <joint name="rail_to_base" type="prismatic">
    <parent link="rail" />
    <child link="base_link" />
    <origin xyz="0 0 ${0.5*rail_cross_section}"/>
    <axis xyz="1 0 0"/>
    <limit lower="-2" upper="2" effort="1" velocity="1"/>
  </joint>

  <joint name="world_to_cylinder" type="fixed">
    <parent link="world" />
    <child link="obstacle_cylinder" />
    <origin xyz="0 1.5 ${0.5*cylinder_height}"/>
  </joint>
</robot>

